version: '3.5'

services:
  db:
    container_name: mysql-db-1
    image: mysql
    expose:
      - '3306'
    ports:
      - '3306:3306'
    environment:
      MYSQL_DATABASE: database-example
      MYSQL_PASSWORD: root
      MYSQL_USER: db_user
      MYSQL_ROOT_PASSWORD: root
    restart: always